version: '3'

services:
  sqlcontainer:
    image: mysql:5.7
    restart: always
    env_file: ./app/.env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service1
      MYSQL_USER: root_user
      MYSQL_PASSWORD: abc123
    ports:
      - 6033:3306
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: timdanderson1/fecservice1
    env_file: ./app/.env
    ports:
      - 4052:4052
    depends_on:
      - sqlcontainer
    stdin_open: true
    tty: true

volumes:
  db-config:
  db-data: